let test_bagrules = [
  { bagColor: "shiny gold", contain: "2 dark red bags" },
  { bagColor: "dark red", contain: "2 dark orange bags" },
  { bagColor: "dark orange", contain: "2 dark yellow bags" },
  { bagColor: "dark yellow", contain: "2 dark green bags" },
  { bagColor: "dark green", contain: "2 dark blue bags" },
  { bagColor: "dark blue", contain: "2 dark violet bags" },
  { bagColor: "dark violet", contain: "no other bags" }
]

let puzzle_bagrules = [
  { bagColor: "muted lavender", contain: "5 dull brown bags, 4 pale maroon bags, 2 drab orange bags." },
  { bagColor: "plaid aqua", contain: "1 posh violet bag, 5 pale yellow bags, 4 bright salmon bags." },
  { bagColor: "wavy lime", contain: "3 vibrant indigo bags, 1 posh gray bag." },
  { bagColor: "pale coral", contain: "5 mirrored olive bags, 2 posh salmon bags." },
  { bagColor: "faded chartreuse", contain: "1 plaid blue bag, 4 clear salmon bags, 5 muted teal bags." },
  { bagColor: "vibrant indigo", contain: "4 pale red bags, 1 vibrant violet bag." },
  { bagColor: "vibrant salmon", contain: "1 dull crimson bag, 5 dim coral bags, 4 pale salmon bags, 3 pale fuchsia bags." },
  { bagColor: "light yellow", contain: "5 clear beige bags, 3 dotted beige bags." },
  { bagColor: "muted plum", contain: "5 posh silver bags, 3 pale turquoise bags, 3 faded chartreuse bags." },
  { bagColor: "mirrored indigo", contain: "4 pale tan bags, 1 posh indigo bag, 3 shiny salmon bags, 4 wavy indigo bags." },
  { bagColor: "pale indigo", contain: "3 dark white bags." },
  { bagColor: "plaid indigo", contain: "4 mirrored teal bags." },
  { bagColor: "shiny brown", contain: "1 striped gold bag." },
  { bagColor: "drab violet", contain: "1 drab magenta bag, 5 posh orange bags, 1 mirrored brown bag, 4 wavy salmon bags." },
  { bagColor: "pale olive", contain: "2 light black bags, 2 faded tomato bags." },
  { bagColor: "dark teal", contain: "3 striped fuchsia bags." },
  { bagColor: "plaid white", contain: "4 shiny salmon bags." },
  { bagColor: "muted gold", contain: "5 faded lavender bags, 3 striped aqua bags." },
  { bagColor: "pale cyan", contain: "3 muted tan bags, 5 bright purple bags, 1 posh blue bag." },
  { bagColor: "pale tan", contain: "3 bright teal bags." },
  { bagColor: "bright aqua", contain: "5 plaid magenta bags, 5 muted lavender bags, 4 dim turquoise bags, 1 shiny turquoise bag." },
  { bagColor: "dark gold", contain: "4 dull indigo bags, 5 mirrored orange bags, 5 bright teal bags, 1 dim gold bag." },
  { bagColor: "muted salmon", contain: "3 muted gray bags, 4 pale salmon bags." },
  { bagColor: "striped plum", contain: "1 dark indigo bag, 1 vibrant violet bag." },
  { bagColor: "posh yellow", contain: "3 shiny tan bags, 4 dull lavender bags, 5 pale yellow bags." },
  { bagColor: "plaid lime", contain: "2 bright brown bags, 4 dull lavender bags." },
  { bagColor: "mirrored gray", contain: "4 mirrored teal bags, 3 muted indigo bags." },
  { bagColor: "muted olive", contain: "3 dim fuchsia bags, 2 dim salmon bags, 4 shiny maroon bags." },
  { bagColor: "dotted blue", contain: "4 plaid orange bags, 5 faded black bags, 2 muted black bags, 5 mirrored lime bags." },
  { bagColor: "wavy beige", contain: "5 dark aqua bags, 3 mirrored lavender bags, 3 drab fuchsia bags." },
  { bagColor: "shiny indigo", contain: "3 wavy black bags, 2 dull plum bags." },
  { bagColor: "drab lavender", contain: "4 mirrored chartreuse bags." },
  { bagColor: "vibrant tomato", contain: "3 wavy white bags, 1 dull plum bag." },
  { bagColor: "plaid teal", contain: "3 mirrored bronze bags." },
  { bagColor: "pale chartreuse", contain: "no other bags." },
  { bagColor: "muted coral", contain: "1 striped lavender bag, 5 dotted crimson bags, 2 faded tomato bags." },
  { bagColor: "faded aqua", contain: "2 bright plum bags, 3 faded gold bags, 1 mirrored bronze bag, 2 dull lavender bags." },
  { bagColor: "pale brown", contain: "1 clear salmon bag, 4 drab tan bags, 1 light orange bag, 1 light silver bag." },
  { bagColor: "drab orange", contain: "3 faded beige bags." },
  { bagColor: "pale blue", contain: "3 pale plum bags, 3 dotted green bags, 4 dark lime bags, 5 clear beige bags." },
  { bagColor: "dull purple", contain: "5 posh aqua bags, 1 muted blue bag, 1 bright gray bag, 1 muted chartreuse bag." },
  { bagColor: "bright silver", contain: "5 dark turquoise bags, 2 dark teal bags, 1 muted tan bag, 3 vibrant tan bags." },
  { bagColor: "dim silver", contain: "4 plaid black bags." },
  { bagColor: "faded violet", contain: "5 dark maroon bags." },
  { bagColor: "pale maroon", contain: "5 dark maroon bags, 4 drab chartreuse bags." },
  { bagColor: "shiny green", contain: "1 bright chartreuse bag." },
  { bagColor: "vibrant crimson", contain: "3 dotted red bags, 2 striped violet bags, 1 light bronze bag." },
  { bagColor: "clear lavender", contain: "1 faded teal bag, 5 clear cyan bags." },
  { bagColor: "mirrored red", contain: "2 dim gray bags, 2 drab orange bags, 4 muted purple bags, 3 muted white bags." },
  { bagColor: "striped green", contain: "2 light purple bags, 4 light gold bags, 3 posh magenta bags." },
  { bagColor: "dim yellow", contain: "1 light crimson bag, 2 muted indigo bags." },
  { bagColor: "dotted orange", contain: "3 wavy salmon bags, 1 dim fuchsia bag." },
  { bagColor: "vibrant gray", contain: "1 plaid brown bag, 5 mirrored black bags, 4 plaid olive bags." },
  { bagColor: "mirrored silver", contain: "2 striped magenta bags, 3 striped coral bags." },
  { bagColor: "pale magenta", contain: "4 posh tomato bags, 4 plaid blue bags, 2 shiny gold bags, 3 faded beige bags." },
  { bagColor: "vibrant black", contain: "4 dotted brown bags." },
  { bagColor: "muted violet", contain: "1 clear tomato bag, 1 striped beige bag." },
  { bagColor: "clear salmon", contain: "1 drab chartreuse bag, 4 dotted beige bags, 5 light crimson bags, 3 dotted orange bags." },
  { bagColor: "posh indigo", contain: "3 mirrored teal bags, 5 drab gold bags." },
  { bagColor: "wavy black", contain: "5 dotted purple bags, 5 plaid chartreuse bags, 3 striped gold bags." },
  { bagColor: "mirrored lavender", contain: "2 dim black bags." },
  { bagColor: "shiny maroon", contain: "2 dotted beige bags." },
  { bagColor: "drab magenta", contain: "2 dim yellow bags." },
  { bagColor: "pale orange", contain: "1 shiny purple bag, 5 striped turquoise bags, 2 light crimson bags." },
  { bagColor: "shiny beige", contain: "5 clear white bags, 2 striped turquoise bags, 4 pale yellow bags, 1 muted black bag." },
  { bagColor: "striped cyan", contain: "2 plaid yellow bags, 2 clear teal bags, 3 wavy olive bags, 4 posh violet bags." },
  { bagColor: "dull cyan", contain: "1 striped salmon bag." },
  { bagColor: "vibrant green", contain: "4 dull coral bags, 4 drab yellow bags, 4 dark cyan bags." },
  { bagColor: "wavy cyan", contain: "5 light salmon bags, 5 dim blue bags, 2 pale green bags, 1 faded indigo bag." },
  { bagColor: "drab plum", contain: "3 dark magenta bags." },
  { bagColor: "light aqua", contain: "4 bright bronze bags, 3 wavy lavender bags, 3 dull cyan bags, 2 bright green bags." },
  { bagColor: "pale plum", contain: "5 clear plum bags." },
  { bagColor: "vibrant silver", contain: "1 dim lavender bag, 4 bright teal bags." },
  { bagColor: "wavy white", contain: "1 light crimson bag, 4 wavy salmon bags." },
  { bagColor: "shiny chartreuse", contain: "2 plaid gray bags, 5 mirrored white bags." },
  { bagColor: "dull chartreuse", contain: "1 dull cyan bag, 3 striped white bags, 4 posh indigo bags." },
  { bagColor: "clear magenta", contain: "1 plaid coral bag, 5 light plum bags, 1 bright yellow bag." },
  { bagColor: "muted white", contain: "2 dull salmon bags, 5 bright turquoise bags, 3 wavy gray bags, 1 plaid black bag." },
  { bagColor: "dull brown", contain: "3 faded lavender bags." },
  { bagColor: "muted turquoise", contain: "4 mirrored plum bags, 4 mirrored brown bags, 4 drab salmon bags, 4 mirrored tomato bags." },
  { bagColor: "posh tomato", contain: "2 drab orange bags, 4 dim lavender bags." },
  { bagColor: "shiny fuchsia", contain: "3 dull black bags, 5 wavy coral bags." },
  { bagColor: "dim gray", contain: "3 drab gray bags." },
  { bagColor: "striped olive", contain: "5 light purple bags, 5 wavy yellow bags, 1 striped fuchsia bag." },
  { bagColor: "muted maroon", contain: "2 bright white bags." },
  { bagColor: "light tomato", contain: "1 striped indigo bag, 5 plaid plum bags, 4 clear indigo bags, 4 drab tan bags." },
  { bagColor: "plaid violet", contain: "2 dim coral bags." },
  { bagColor: "striped chartreuse", contain: "2 shiny gray bags." },
  { bagColor: "mirrored white", contain: "4 striped beige bags." },
  { bagColor: "dim beige", contain: "3 wavy bronze bags, 4 vibrant silver bags, 1 striped white bag, 2 dark plum bags." },
  { bagColor: "striped violet", contain: "5 dull teal bags, 2 vibrant red bags." },
  { bagColor: "drab green", contain: "1 striped olive bag, 2 light salmon bags, 1 faded cyan bag, 3 vibrant fuchsia bags." },
  { bagColor: "clear lime", contain: "2 plaid coral bags, 1 light lavender bag, 4 posh salmon bags." },
  { bagColor: "striped indigo", contain: "2 pale maroon bags, 5 dotted aqua bags, 3 drab gray bags." },
  { bagColor: "dim blue", contain: "5 faded bronze bags, 4 dark blue bags." },
  { bagColor: "faded fuchsia", contain: "3 muted fuchsia bags, 1 light orange bag, 2 striped beige bags, 1 dotted red bag." },
  { bagColor: "plaid red", contain: "5 pale maroon bags, 3 dark beige bags, 2 striped fuchsia bags." },
  { bagColor: "drab silver", contain: "1 dim salmon bag, 2 shiny salmon bags." },
  { bagColor: "dark chartreuse", contain: "1 dull aqua bag." },
  { bagColor: "clear chartreuse", contain: "5 faded brown bags, 3 dotted aqua bags." },
  { bagColor: "plaid silver", contain: "5 pale red bags." },
  { bagColor: "wavy chartreuse", contain: "5 mirrored red bags, 1 dull teal bag." },
  { bagColor: "clear gray", contain: "5 striped salmon bags, 5 plaid silver bags, 1 clear black bag." },
  { bagColor: "shiny white", contain: "1 shiny gray bag, 5 vibrant gray bags." },
  { bagColor: "posh coral", contain: "2 muted white bags." },
  { bagColor: "light red", contain: "5 muted indigo bags, 1 wavy fuchsia bag." },
  { bagColor: "dull fuchsia", contain: "4 light plum bags, 4 faded red bags." },
  { bagColor: "dotted gold", contain: "1 plaid brown bag, 4 dotted aqua bags, 2 pale purple bags." },
  { bagColor: "faded orange", contain: "3 dotted beige bags." },
  { bagColor: "bright coral", contain: "2 dark cyan bags, 1 wavy tan bag, 1 vibrant yellow bag." },
  { bagColor: "striped brown", contain: "5 light yellow bags, 4 dull indigo bags, 4 clear maroon bags." },
  { bagColor: "light fuchsia", contain: "3 dotted gray bags, 1 striped orange bag, 1 mirrored olive bag, 2 wavy fuchsia bags." },
  { bagColor: "dotted bronze", contain: "2 dull salmon bags." },
  { bagColor: "faded red", contain: "2 posh indigo bags, 5 dotted aqua bags." },
  { bagColor: "wavy teal", contain: "3 faded tomato bags, 4 dark silver bags, 3 shiny cyan bags." },
  { bagColor: "dim tomato", contain: "4 wavy silver bags, 3 drab red bags." },
  { bagColor: "muted beige", contain: "1 bright gray bag, 1 dark red bag." },
  { bagColor: "shiny yellow", contain: "2 light plum bags." },
  { bagColor: "wavy indigo", contain: "1 faded red bag, 1 plaid yellow bag, 2 dull aqua bags." },
  { bagColor: "plaid maroon", contain: "5 vibrant beige bags." },
  { bagColor: "wavy tan", contain: "5 plaid maroon bags." },
  { bagColor: "striped coral", contain: "1 pale silver bag, 4 clear beige bags, 3 dotted aqua bags, 3 striped turquoise bags." },
  { bagColor: "shiny black", contain: "1 clear silver bag, 1 mirrored blue bag." },
  { bagColor: "muted silver", contain: "1 posh teal bag, 4 faded teal bags, 4 plaid aqua bags, 2 striped olive bags." },
  { bagColor: "pale gray", contain: "4 dotted silver bags." },
  { bagColor: "light white", contain: "2 dull salmon bags, 5 vibrant violet bags, 1 dull black bag." },
  { bagColor: "mirrored beige", contain: "3 dark teal bags, 3 wavy coral bags, 3 plaid black bags." },
  { bagColor: "mirrored tomato", contain: "5 muted bronze bags, 2 drab gold bags, 4 dark plum bags." },
  { bagColor: "dull magenta", contain: "1 wavy black bag, 5 dull gray bags." },
  { bagColor: "pale crimson", contain: "3 wavy brown bags, 5 dark green bags, 3 pale fuchsia bags." },
  { bagColor: "pale beige", contain: "3 posh black bags, 4 dotted gold bags, 1 plaid blue bag." },
  { bagColor: "dull red", contain: "2 light chartreuse bags, 1 striped tomato bag, 4 plaid green bags, 3 dull chartreuse bags." },
  { bagColor: "dotted violet", contain: "4 dark plum bags, 3 dull plum bags, 4 pale red bags." },
  { bagColor: "muted bronze", contain: "2 muted teal bags, 5 shiny purple bags, 4 pale chartreuse bags, 4 wavy salmon bags." },
  { bagColor: "dark coral", contain: "5 dull indigo bags, 1 vibrant plum bag, 2 mirrored black bags, 4 drab gold bags." },
  { bagColor: "shiny magenta", contain: "5 light turquoise bags, 4 striped olive bags." },
  { bagColor: "faded olive", contain: "2 clear white bags." },
  { bagColor: "pale aqua", contain: "2 vibrant fuchsia bags." },
  { bagColor: "vibrant yellow", contain: "4 muted teal bags, 1 mirrored teal bag." },
  { bagColor: "dotted lime", contain: "5 dotted white bags, 2 wavy aqua bags, 3 pale salmon bags." },
  { bagColor: "dark bronze", contain: "1 clear beige bag, 1 muted olive bag." },
  { bagColor: "dim lavender", contain: "1 dull indigo bag, 2 shiny purple bags, 4 dull teal bags." },
  { bagColor: "wavy gold", contain: "5 dull black bags, 1 muted fuchsia bag, 4 dark red bags, 1 light crimson bag." },
  { bagColor: "striped crimson", contain: "5 shiny gray bags, 3 mirrored crimson bags, 2 drab chartreuse bags, 4 dull aqua bags." },
  { bagColor: "dark aqua", contain: "1 bright indigo bag, 5 muted white bags, 2 shiny crimson bags, 3 mirrored orange bags." },
  { bagColor: "posh black", contain: "3 pale tan bags, 1 dim brown bag, 5 clear green bags." },
  { bagColor: "bright beige", contain: "4 dotted black bags." },
  { bagColor: "dull maroon", contain: "1 drab red bag, 4 faded turquoise bags, 1 pale olive bag." },
  { bagColor: "dull salmon", contain: "3 mirrored olive bags, 3 dull indigo bags, 1 dim brown bag, 4 shiny lime bags." },
  { bagColor: "faded purple", contain: "4 faded indigo bags." },
  { bagColor: "light beige", contain: "1 posh gray bag, 3 dotted white bags, 1 striped silver bag." },
  { bagColor: "vibrant magenta", contain: "4 drab red bags, 1 dotted white bag, 5 striped aqua bags." },
  { bagColor: "light maroon", contain: "1 dull black bag." },
  { bagColor: "light olive", contain: "3 dull tan bags." },
  { bagColor: "vibrant lime", contain: "2 dim lavender bags." },
  { bagColor: "muted aqua", contain: "3 bright olive bags, 1 muted teal bag, 3 dull crimson bags." },
  { bagColor: "dotted beige", contain: "no other bags." },
  { bagColor: "dotted indigo", contain: "2 light lavender bags, 5 dark white bags, 3 wavy gray bags, 4 plaid chartreuse bags." },
  { bagColor: "drab yellow", contain: "4 mirrored aqua bags, 5 plaid olive bags, 5 dull black bags, 4 striped turquoise bags." },
  { bagColor: "light lime", contain: "3 striped turquoise bags, 4 muted coral bags, 5 muted yellow bags, 4 mirrored silver bags." },
  { bagColor: "dark crimson", contain: "2 light bronze bags, 1 vibrant chartreuse bag." },
  { bagColor: "clear plum", contain: "1 muted indigo bag, 5 dim red bags, 2 pale orange bags, 5 light black bags." },
  { bagColor: "mirrored violet", contain: "3 wavy salmon bags." },
  { bagColor: "striped silver", contain: "5 bright olive bags, 5 dim brown bags, 2 posh blue bags, 1 posh purple bag." },
  { bagColor: "posh gold", contain: "5 faded lavender bags." },
  { bagColor: "striped lime", contain: "4 striped coral bags." },
  { bagColor: "plaid tomato", contain: "2 dull white bags, 1 wavy white bag, 5 drab red bags." },
  { bagColor: "drab tan", contain: "1 mirrored bronze bag, 1 mirrored tomato bag, 2 mirrored green bags." },
  { bagColor: "posh purple", contain: "4 dull cyan bags." },
  { bagColor: "plaid blue", contain: "2 muted fuchsia bags, 1 bright teal bag, 2 pale chartreuse bags." },
  { bagColor: "dim lime", contain: "4 drab gold bags, 1 muted fuchsia bag, 1 posh tomato bag." },
  { bagColor: "dark white", contain: "2 wavy gold bags." },
  { bagColor: "bright red", contain: "4 light fuchsia bags, 1 plaid orange bag, 1 pale red bag." },
  { bagColor: "wavy blue", contain: "4 striped red bags, 1 mirrored black bag." },
  { bagColor: "light teal", contain: "1 faded orange bag, 5 muted white bags." },
  { bagColor: "shiny blue", contain: "1 drab red bag, 3 shiny brown bags, 2 dark teal bags, 2 dotted silver bags." },
  { bagColor: "bright gray", contain: "3 muted teal bags, 2 clear plum bags, 5 light olive bags, 5 dark red bags." },
  { bagColor: "bright black", contain: "5 posh yellow bags, 1 striped maroon bag." },
  { bagColor: "shiny gold", contain: "3 wavy gold bags, 2 plaid chartreuse bags, 2 shiny lime bags, 5 dull indigo bags." },
  { bagColor: "striped teal", contain: "4 dark lime bags, 4 light yellow bags, 2 dull brown bags." },
  { bagColor: "wavy coral", contain: "3 dim yellow bags, 1 clear red bag, 4 pale chartreuse bags." },
  { bagColor: "plaid chartreuse", contain: "1 striped maroon bag, 5 dotted yellow bags." },
  { bagColor: "pale turquoise", contain: "3 clear yellow bags, 2 dim coral bags." },
  { bagColor: "vibrant plum", contain: "3 dotted yellow bags." },
  { bagColor: "drab cyan", contain: "5 vibrant green bags." },
  { bagColor: "wavy crimson", contain: "1 mirrored gray bag, 2 dim teal bags." },
  { bagColor: "wavy maroon", contain: "3 pale tan bags." },
  { bagColor: "light orange", contain: "4 vibrant silver bags, 2 dim olive bags, 2 drab red bags." },
  { bagColor: "plaid brown", contain: "2 bright turquoise bags, 4 shiny tan bags, 2 dull indigo bags, 3 plaid olive bags." },
  { bagColor: "posh silver", contain: "5 wavy coral bags." },
  { bagColor: "wavy bronze", contain: "1 plaid yellow bag, 1 dim gold bag." },
  { bagColor: "shiny violet", contain: "5 plaid coral bags, 2 mirrored brown bags." },
  { bagColor: "posh lime", contain: "3 wavy bronze bags, 2 striped tomato bags, 2 pale tan bags." },
  { bagColor: "dim salmon", contain: "3 dim brown bags, 5 drab chartreuse bags." },
  { bagColor: "faded beige", contain: "no other bags." },
  { bagColor: "dotted gray", contain: "5 dark lime bags, 2 posh black bags, 3 muted fuchsia bags." },
  { bagColor: "dull crimson", contain: "5 vibrant fuchsia bags." },
  { bagColor: "drab brown", contain: "5 pale maroon bags, 5 light crimson bags." },
  { bagColor: "bright blue", contain: "5 vibrant brown bags." },
  { bagColor: "bright violet", contain: "1 light white bag, 5 clear beige bags, 2 dull crimson bags." },
  { bagColor: "plaid magenta", contain: "2 light plum bags, 1 wavy white bag, 5 pale green bags, 1 bright tomato bag." },
  { bagColor: "faded silver", contain: "5 light black bags, 5 mirrored teal bags, 5 vibrant plum bags." },
  { bagColor: "wavy brown", contain: "4 faded gray bags, 3 dotted olive bags, 1 light silver bag." },
  { bagColor: "clear teal", contain: "2 mirrored black bags, 2 wavy gold bags, 2 striped red bags, 5 light silver bags." },
  { bagColor: "posh crimson", contain: "5 drab tan bags." },
  { bagColor: "clear fuchsia", contain: "4 faded tomato bags, 1 dotted beige bag." },
  { bagColor: "bright maroon", contain: "2 wavy teal bags, 2 shiny gray bags, 5 dull gray bags, 3 dull teal bags." },
  { bagColor: "drab gray", contain: "3 dark white bags, 2 pale salmon bags, 4 bright teal bags." },
  { bagColor: "vibrant brown", contain: "4 wavy salmon bags." },
  { bagColor: "bright green", contain: "2 clear cyan bags, 3 wavy lavender bags, 2 plaid blue bags, 2 faded gold bags." },
  { bagColor: "light salmon", contain: "1 muted tan bag, 5 plaid plum bags." },
  { bagColor: "plaid bronze", contain: "4 mirrored chartreuse bags, 3 plaid turquoise bags, 2 wavy orange bags, 5 dotted yellow bags." },
  { bagColor: "dull bronze", contain: "2 vibrant lime bags, 2 muted purple bags, 2 dark magenta bags." },
  { bagColor: "bright orange", contain: "4 pale violet bags, 2 light fuchsia bags, 3 dull purple bags." },
  { bagColor: "wavy fuchsia", contain: "4 dotted olive bags, 1 dull brown bag." },
  { bagColor: "mirrored olive", contain: "4 muted fuchsia bags, 4 striped turquoise bags." },
  { bagColor: "shiny salmon", contain: "2 dark white bags." },
  { bagColor: "striped tan", contain: "4 mirrored purple bags." },
  { bagColor: "dull coral", contain: "3 posh coral bags, 1 dotted green bag." },
  { bagColor: "drab teal", contain: "4 wavy yellow bags, 5 mirrored aqua bags." },
  { bagColor: "shiny tan", contain: "5 striped maroon bags, 5 vibrant red bags." },
  { bagColor: "bright crimson", contain: "1 muted magenta bag." },
  { bagColor: "shiny lime", contain: "1 faded teal bag, 1 light crimson bag." },
  { bagColor: "posh white", contain: "3 posh orange bags, 4 pale gray bags, 5 dull maroon bags, 5 plaid plum bags." },
  { bagColor: "dotted brown", contain: "1 vibrant indigo bag, 1 plaid olive bag." },
  { bagColor: "faded coral", contain: "5 muted bronze bags, 3 mirrored lavender bags." },
  { bagColor: "faded brown", contain: "1 bright turquoise bag, 3 posh indigo bags, 2 pale fuchsia bags, 3 dark indigo bags." },
  { bagColor: "vibrant aqua", contain: "2 clear beige bags, 3 posh olive bags, 3 dark turquoise bags, 2 posh magenta bags." },
  { bagColor: "dark turquoise", contain: "1 striped gold bag, 1 mirrored red bag." },
  { bagColor: "drab gold", contain: "2 clear beige bags, 4 striped turquoise bags, 1 pale orange bag, 1 clear salmon bag." },
  { bagColor: "mirrored green", contain: "4 dotted beige bags, 3 pale chartreuse bags, 3 light crimson bags." },
  { bagColor: "clear violet", contain: "3 posh orange bags, 4 faded beige bags, 3 drab red bags, 4 shiny salmon bags." },
  { bagColor: "posh plum", contain: "1 shiny white bag, 1 striped lavender bag." },
  { bagColor: "vibrant purple", contain: "5 bright teal bags." },
  { bagColor: "dark salmon", contain: "4 striped olive bags, 5 mirrored crimson bags, 5 plaid lime bags, 3 dark tomato bags." },
  { bagColor: "shiny silver", contain: "2 vibrant red bags." },
  { bagColor: "dull turquoise", contain: "3 faded crimson bags, 1 drab maroon bag, 5 drab gold bags." },
  { bagColor: "dull orange", contain: "1 dark yellow bag, 3 bright beige bags." },
  { bagColor: "bright bronze", contain: "3 posh salmon bags, 1 mirrored violet bag, 2 muted white bags, 3 dotted orange bags." },
  { bagColor: "bright teal", contain: "4 dim fuchsia bags." },
  { bagColor: "clear turquoise", contain: "1 faded teal bag, 2 dull teal bags." },
  { bagColor: "wavy magenta", contain: "4 dim teal bags, 3 mirrored bronze bags, 3 plaid plum bags, 5 wavy lavender bags." },
  { bagColor: "faded bronze", contain: "2 striped salmon bags, 3 dark red bags, 1 dark indigo bag." },
  { bagColor: "faded plum", contain: "1 clear green bag." },
  { bagColor: "faded maroon", contain: "1 striped maroon bag, 5 dim black bags, 1 vibrant indigo bag." },
  { bagColor: "muted teal", contain: "4 light crimson bags, 5 drab chartreuse bags." },
  { bagColor: "vibrant maroon", contain: "3 dark fuchsia bags, 3 plaid turquoise bags, 1 pale silver bag, 4 shiny cyan bags." },
  { bagColor: "plaid crimson", contain: "3 mirrored olive bags." },
  { bagColor: "clear tan", contain: "1 vibrant purple bag, 1 wavy aqua bag." },
  { bagColor: "clear aqua", contain: "4 bright white bags." },
  { bagColor: "striped red", contain: "3 wavy coral bags, 3 dark white bags, 4 muted fuchsia bags, 4 posh tomato bags." },
  { bagColor: "posh violet", contain: "1 muted fuchsia bag, 3 dim coral bags, 2 drab orange bags." },
  { bagColor: "plaid cyan", contain: "2 shiny indigo bags." },
  { bagColor: "light chartreuse", contain: "5 wavy tan bags, 4 clear indigo bags." },
  { bagColor: "vibrant lavender", contain: "3 light gray bags, 4 striped beige bags, 5 dark maroon bags, 3 drab fuchsia bags." },
  { bagColor: "dim red", contain: "4 pale orange bags, 3 drab chartreuse bags." },
  { bagColor: "vibrant turquoise", contain: "3 clear tomato bags, 4 posh blue bags." },
  { bagColor: "muted green", contain: "4 clear bronze bags, 3 dotted black bags, 3 dull beige bags." },
  { bagColor: "faded salmon", contain: "2 drab gold bags, 2 clear red bags, 2 dark indigo bags, 5 plaid teal bags." },
  { bagColor: "posh chartreuse", contain: "4 dotted orange bags." },
  { bagColor: "dotted turquoise", contain: "5 shiny fuchsia bags, 2 vibrant indigo bags, 3 vibrant fuchsia bags, 5 muted green bags." },
  { bagColor: "wavy turquoise", contain: "1 dark white bag, 4 posh tan bags." },
  { bagColor: "clear purple", contain: "2 vibrant gray bags, 3 dark plum bags, 1 shiny fuchsia bag, 4 plaid indigo bags." },
  { bagColor: "pale tomato", contain: "2 striped silver bags, 1 mirrored aqua bag." },
  { bagColor: "pale salmon", contain: "4 muted indigo bags, 4 faded teal bags." },
  { bagColor: "dark maroon", contain: "5 dotted orange bags, 5 faded beige bags, 3 wavy salmon bags, 5 dim lavender bags." },
  { bagColor: "faded green", contain: "3 wavy coral bags, 5 dull indigo bags, 4 dim salmon bags, 1 pale gray bag." },
  { bagColor: "bright gold", contain: "4 drab lavender bags." },
  { bagColor: "dull white", contain: "4 clear salmon bags, 2 shiny gold bags." },
  { bagColor: "drab olive", contain: "3 pale lime bags, 3 striped crimson bags, 5 plaid gray bags, 2 posh magenta bags." },
  { bagColor: "bright cyan", contain: "4 dotted black bags." },
  { bagColor: "drab beige", contain: "4 shiny yellow bags." },
  { bagColor: "dotted salmon", contain: "5 light maroon bags, 5 dotted gray bags." },
  { bagColor: "posh gray", contain: "3 dark red bags, 2 mirrored gray bags, 2 dim brown bags, 4 dotted aqua bags." },
  { bagColor: "dull gray", contain: "2 shiny beige bags, 5 posh silver bags." },
  { bagColor: "light blue", contain: "1 dim coral bag, 5 vibrant plum bags, 1 clear salmon bag, 1 clear yellow bag." },
  { bagColor: "striped gray", contain: "5 striped indigo bags, 1 faded lime bag, 2 light tomato bags." },
  { bagColor: "dark violet", contain: "1 posh gray bag, 5 shiny cyan bags, 2 pale indigo bags, 4 light coral bags." },
  { bagColor: "striped black", contain: "5 dotted maroon bags, 1 drab blue bag." },
  { bagColor: "shiny coral", contain: "1 clear yellow bag, 5 striped plum bags, 4 dull tomato bags." },
  { bagColor: "faded tan", contain: "5 vibrant bronze bags, 5 muted fuchsia bags, 1 pale coral bag, 4 dull indigo bags." },
  { bagColor: "pale white", contain: "4 clear cyan bags, 2 bright yellow bags, 4 vibrant tomato bags." },
  { bagColor: "plaid plum", contain: "5 pale violet bags, 3 posh yellow bags, 3 faded silver bags." },
  { bagColor: "bright fuchsia", contain: "5 clear black bags." },
  { bagColor: "dotted red", contain: "3 dark magenta bags, 5 clear indigo bags, 1 faded bronze bag, 4 dotted gray bags." },
  { bagColor: "plaid turquoise", contain: "2 dark indigo bags." },
  { bagColor: "pale lavender", contain: "4 posh fuchsia bags, 1 clear black bag, 4 wavy lime bags." },
  { bagColor: "bright lavender", contain: "2 wavy magenta bags, 5 plaid blue bags, 1 drab yellow bag, 1 muted gray bag." },
  { bagColor: "bright white", contain: "4 light gray bags." },
  { bagColor: "dull black", contain: "2 shiny lime bags, 3 muted indigo bags, 5 faded beige bags." },
  { bagColor: "muted tomato", contain: "2 dark yellow bags." },
  { bagColor: "plaid fuchsia", contain: "2 dull lavender bags." },
  { bagColor: "dark indigo", contain: "2 dim lavender bags, 3 shiny maroon bags." },
  { bagColor: "mirrored magenta", contain: "1 mirrored chartreuse bag." },
  { bagColor: "vibrant violet", contain: "5 dotted beige bags, 5 plaid olive bags." },
  { bagColor: "pale lime", contain: "1 vibrant silver bag, 4 shiny white bags, 2 wavy orange bags, 3 plaid coral bags." },
  { bagColor: "mirrored aqua", contain: "5 light yellow bags, 3 plaid silver bags, 2 dark white bags, 2 dull teal bags." },
  { bagColor: "striped turquoise", contain: "1 bright turquoise bag, 2 faded beige bags." },
  { bagColor: "faded indigo", contain: "2 dotted purple bags." },
  { bagColor: "plaid green", contain: "3 dim orange bags." },
  { bagColor: "dotted lavender", contain: "5 dotted crimson bags, 5 bright turquoise bags, 3 muted lavender bags, 4 mirrored olive bags." },
  { bagColor: "muted tan", contain: "2 faded orange bags, 5 mirrored gray bags, 1 faded green bag." },
  { bagColor: "dark plum", contain: "2 mirrored olive bags, 4 muted fuchsia bags, 2 shiny maroon bags, 1 dim fuchsia bag." },
  { bagColor: "light cyan", contain: "4 dotted gray bags, 4 wavy red bags, 1 dull white bag." },
  { bagColor: "striped gold", contain: "2 wavy silver bags, 2 muted purple bags, 3 wavy coral bags." },
  { bagColor: "striped white", contain: "4 wavy coral bags, 4 pale plum bags, 2 wavy black bags, 5 dim olive bags." },
  { bagColor: "mirrored yellow", contain: "3 plaid chartreuse bags, 4 muted gold bags, 1 mirrored bronze bag." },
  { bagColor: "clear tomato", contain: "3 striped indigo bags, 3 dim fuchsia bags, 2 wavy gray bags." },
  { bagColor: "faded teal", contain: "no other bags." },
  { bagColor: "faded lavender", contain: "2 clear bronze bags, 3 muted teal bags, 2 dotted yellow bags, 5 shiny purple bags." },
  { bagColor: "posh lavender", contain: "5 posh gray bags." },
  { bagColor: "bright brown", contain: "2 dull crimson bags, 5 muted bronze bags, 4 dark indigo bags, 5 mirrored orange bags." },
  { bagColor: "faded crimson", contain: "3 dotted crimson bags." },
  { bagColor: "mirrored teal", contain: "1 plaid blue bag, 1 clear red bag, 5 striped turquoise bags, 4 dotted beige bags." },
  { bagColor: "dark fuchsia", contain: "1 faded green bag." },
  { bagColor: "dim coral", contain: "5 clear salmon bags, 4 dotted beige bags, 1 pale salmon bag, 2 plaid chartreuse bags." },
  { bagColor: "posh blue", contain: "3 pale maroon bags, 5 dim coral bags." },
  { bagColor: "light indigo", contain: "1 vibrant silver bag, 1 bright chartreuse bag, 1 light black bag." },
  { bagColor: "shiny lavender", contain: "4 dotted olive bags, 5 faded brown bags, 1 plaid tomato bag." },
  { bagColor: "dotted white", contain: "4 dim olive bags." },
  { bagColor: "dotted chartreuse", contain: "4 striped turquoise bags, 1 dotted silver bag." },
  { bagColor: "faded black", contain: "2 muted white bags, 3 drab teal bags, 3 wavy gray bags." },
  { bagColor: "vibrant white", contain: "4 dark white bags, 4 clear violet bags, 3 plaid magenta bags, 5 dark green bags." },
  { bagColor: "faded magenta", contain: "3 faded green bags, 4 plaid olive bags, 5 plaid brown bags, 1 wavy salmon bag." },
  { bagColor: "dull plum", contain: "3 muted purple bags." },
  { bagColor: "dim indigo", contain: "5 dotted fuchsia bags, 5 drab red bags, 1 dull green bag, 5 dim fuchsia bags." },
  { bagColor: "pale yellow", contain: "4 mirrored bronze bags." },
  { bagColor: "light violet", contain: "5 dull black bags." },
  { bagColor: "posh green", contain: "1 plaid plum bag, 3 pale violet bags, 5 muted salmon bags." },
  { bagColor: "mirrored purple", contain: "3 mirrored aqua bags, 1 plaid blue bag." },
  { bagColor: "clear orange", contain: "3 light beige bags." },
  { bagColor: "striped tomato", contain: "4 dark orange bags, 1 bright aqua bag." },
  { bagColor: "dark gray", contain: "1 posh violet bag." },
  { bagColor: "plaid beige", contain: "5 pale beige bags." },
  { bagColor: "plaid gray", contain: "3 mirrored bronze bags, 3 clear green bags, 5 dark chartreuse bags." },
  { bagColor: "mirrored coral", contain: "1 pale tan bag, 2 plaid coral bags, 5 striped bronze bags." },
  { bagColor: "dull silver", contain: "1 vibrant purple bag, 3 drab lavender bags, 2 mirrored salmon bags." },
  { bagColor: "clear yellow", contain: "1 shiny gold bag, 4 dotted beige bags, 4 dark lime bags." },
  { bagColor: "light gold", contain: "3 shiny white bags, 4 dim violet bags, 1 light olive bag." },
  { bagColor: "drab white", contain: "5 shiny lavender bags, 4 dotted lavender bags." },
  { bagColor: "faded yellow", contain: "2 dull crimson bags, 3 muted indigo bags, 2 plaid crimson bags, 3 clear green bags." },
  { bagColor: "light gray", contain: "2 plaid orange bags, 5 plaid lavender bags." },
  { bagColor: "dim bronze", contain: "1 vibrant coral bag, 1 wavy teal bag, 1 pale crimson bag." },
  { bagColor: "shiny gray", contain: "5 light lavender bags, 3 drab red bags, 1 plaid chartreuse bag." },
  { bagColor: "striped beige", contain: "3 light black bags, 1 dull teal bag." },
  { bagColor: "dotted fuchsia", contain: "3 faded indigo bags, 2 dim gray bags." },
  { bagColor: "plaid yellow", contain: "4 pale maroon bags, 5 dull black bags, 1 plaid chartreuse bag, 3 drab orange bags." },
  { bagColor: "muted orange", contain: "3 muted lavender bags." },
  { bagColor: "muted crimson", contain: "4 muted cyan bags, 1 dull plum bag." },
  { bagColor: "muted red", contain: "5 faded turquoise bags, 5 light silver bags, 5 dotted aqua bags." },
  { bagColor: "vibrant chartreuse", contain: "4 wavy violet bags, 1 plaid beige bag, 2 clear cyan bags, 2 dull lavender bags." },
  { bagColor: "pale fuchsia", contain: "3 plaid blue bags, 3 muted bronze bags, 4 faded blue bags." },
  { bagColor: "dotted tomato", contain: "4 dark tomato bags, 3 plaid orange bags, 5 posh teal bags." },
  { bagColor: "dim green", contain: "1 dull white bag." },
  { bagColor: "dim aqua", contain: "2 light silver bags, 3 faded silver bags, 3 dotted orange bags, 4 vibrant salmon bags." },
  { bagColor: "dim brown", contain: "no other bags." },
  { bagColor: "muted chartreuse", contain: "2 dark coral bags, 5 striped plum bags." },
  { bagColor: "drab indigo", contain: "2 posh brown bags." },
  { bagColor: "dark orange", contain: "4 plaid blue bags, 1 dark brown bag, 2 striped indigo bags, 1 dark magenta bag." },
  { bagColor: "bright yellow", contain: "3 clear tomato bags." },
  { bagColor: "clear bronze", contain: "4 wavy salmon bags." },
  { bagColor: "dotted olive", contain: "4 striped beige bags, 3 drab orange bags, 3 bright teal bags." },
  { bagColor: "dull violet", contain: "4 plaid salmon bags, 5 faded olive bags." },
  { bagColor: "clear white", contain: "2 plaid coral bags, 1 muted indigo bag, 1 striped beige bag." },
  { bagColor: "dull tan", contain: "5 dim red bags, 5 posh gold bags, 2 clear red bags." },
  { bagColor: "mirrored plum", contain: "4 dim beige bags." },
  { bagColor: "wavy purple", contain: "2 posh silver bags, 5 shiny tan bags, 3 pale red bags, 3 dull salmon bags." },
  { bagColor: "dim black", contain: "3 light yellow bags." },
  { bagColor: "dotted coral", contain: "3 pale violet bags." },
  { bagColor: "posh bronze", contain: "1 posh tomato bag, 1 drab purple bag, 3 dim fuchsia bags, 2 bright brown bags." },
  { bagColor: "wavy salmon", contain: "no other bags." },
  { bagColor: "dull blue", contain: "5 dark plum bags, 4 light yellow bags." },
  { bagColor: "faded lime", contain: "2 dim red bags, 3 drab lavender bags, 5 muted black bags, 2 light coral bags." },
  { bagColor: "vibrant coral", contain: "4 muted purple bags, 5 pale chartreuse bags, 5 dotted black bags." },
  { bagColor: "mirrored chartreuse", contain: "5 muted olive bags." },
  { bagColor: "dark lime", contain: "1 dark magenta bag." },
  { bagColor: "light coral", contain: "2 dull lavender bags." },
  { bagColor: "bright lime", contain: "2 wavy bronze bags." },
  { bagColor: "mirrored orange", contain: "1 pale salmon bag, 1 light orange bag." },
  { bagColor: "muted brown", contain: "3 clear beige bags, 1 faded salmon bag, 2 vibrant cyan bags, 4 clear white bags." },
  { bagColor: "posh orange", contain: "2 dark lime bags, 3 wavy purple bags." },
  { bagColor: "posh magenta", contain: "2 dark teal bags." },
  { bagColor: "drab salmon", contain: "5 drab tomato bags." },
  { bagColor: "muted fuchsia", contain: "no other bags." },
  { bagColor: "wavy tomato", contain: "4 wavy black bags, 4 faded teal bags." },
  { bagColor: "dim chartreuse", contain: "5 drab green bags, 4 drab magenta bags." },
  { bagColor: "dotted crimson", contain: "2 dark white bags, 5 wavy black bags, 4 dull crimson bags." },
  { bagColor: "posh maroon", contain: "4 plaid silver bags, 4 vibrant lime bags, 4 posh gray bags, 3 dull maroon bags." },
  { bagColor: "dull green", contain: "5 muted tan bags, 5 drab red bags." },
  { bagColor: "clear maroon", contain: "3 faded brown bags." },
  { bagColor: "striped yellow", contain: "4 faded lavender bags, 1 wavy coral bag, 5 clear maroon bags." },
  { bagColor: "dull tomato", contain: "2 shiny white bags, 2 light silver bags, 4 dotted chartreuse bags, 4 dark brown bags." },
  { bagColor: "drab chartreuse", contain: "3 dotted beige bags, 3 pale chartreuse bags, 2 muted fuchsia bags, 5 light crimson bags." },
  { bagColor: "plaid purple", contain: "3 drab yellow bags." },
  { bagColor: "light plum", contain: "1 dotted aqua bag, 2 dark white bags." },
  { bagColor: "mirrored brown", contain: "3 mirrored teal bags, 2 dull cyan bags." },
  { bagColor: "mirrored crimson", contain: "3 dull chartreuse bags, 2 dark silver bags, 5 bright cyan bags, 4 dark tomato bags." },
  { bagColor: "dull gold", contain: "4 muted salmon bags." },
  { bagColor: "wavy olive", contain: "3 mirrored brown bags, 5 clear indigo bags." },
  { bagColor: "faded turquoise", contain: "2 clear salmon bags, 2 mirrored gray bags, 1 dark lime bag." },
  { bagColor: "bright indigo", contain: "2 faded lavender bags, 1 shiny gray bag, 4 mirrored indigo bags." },
  { bagColor: "pale teal", contain: "3 dark violet bags, 5 shiny salmon bags." },
  { bagColor: "plaid orange", contain: "5 faded green bags, 5 pale magenta bags." },
  { bagColor: "shiny crimson", contain: "5 shiny green bags, 1 bright tomato bag, 3 vibrant lime bags, 3 clear purple bags." },
  { bagColor: "muted indigo", contain: "4 dim brown bags, 1 dotted beige bag." },
  { bagColor: "dark cyan", contain: "2 striped yellow bags." },
  { bagColor: "dull teal", contain: "1 muted indigo bag, 2 drab chartreuse bags, 5 faded beige bags." },
  { bagColor: "striped fuchsia", contain: "1 mirrored teal bag, 3 dull black bags, 2 dim salmon bags, 5 wavy salmon bags." },
  { bagColor: "drab crimson", contain: "5 dim teal bags, 2 wavy red bags, 3 dark brown bags." },
  { bagColor: "dull olive", contain: "1 clear yellow bag, 4 plaid indigo bags, 4 posh tomato bags, 1 dotted orange bag." },
  { bagColor: "muted lime", contain: "2 light white bags, 5 dotted violet bags, 5 posh gold bags, 2 bright cyan bags." },
  { bagColor: "dark purple", contain: "1 light lavender bag, 2 plaid olive bags, 5 striped maroon bags, 1 dotted gold bag." },
  { bagColor: "dull yellow", contain: "5 mirrored beige bags." },
  { bagColor: "dotted maroon", contain: "3 clear salmon bags, 1 light salmon bag." },
  { bagColor: "dull beige", contain: "5 shiny fuchsia bags." },
  { bagColor: "clear green", contain: "4 muted lavender bags, 5 faded orange bags, 4 faded silver bags, 4 clear red bags." },
  { bagColor: "striped magenta", contain: "2 dotted plum bags." },
  { bagColor: "posh beige", contain: "5 vibrant maroon bags, 1 dim lavender bag." },
  { bagColor: "striped blue", contain: "3 clear turquoise bags, 3 dark purple bags, 3 shiny yellow bags, 5 clear teal bags." },
  { bagColor: "muted magenta", contain: "3 striped orange bags, 5 dim brown bags." },
  { bagColor: "vibrant orange", contain: "1 bright teal bag, 1 drab salmon bag, 5 dull silver bags." },
  { bagColor: "pale violet", contain: "4 shiny tan bags, 2 clear turquoise bags, 2 pale salmon bags, 2 dotted aqua bags." },
  { bagColor: "dotted aqua", contain: "2 striped turquoise bags, 1 dim fuchsia bag, 2 pale chartreuse bags, 2 bright turquoise bags." },
  { bagColor: "clear black", contain: "4 dotted beige bags, 1 dull brown bag, 2 dull teal bags." },
  { bagColor: "light tan", contain: "3 dotted red bags, 1 dark red bag." },
  { bagColor: "pale green", contain: "4 dull salmon bags, 4 dim brown bags." },
  { bagColor: "dim tan", contain: "2 posh silver bags, 2 dark fuchsia bags." },
  { bagColor: "plaid coral", contain: "2 vibrant plum bags, 5 vibrant red bags, 3 dim salmon bags." },
  { bagColor: "wavy lavender", contain: "2 dark gold bags, 5 plaid blue bags, 1 dim yellow bag." },
  { bagColor: "dim violet", contain: "2 clear tan bags, 5 pale magenta bags." },
  { bagColor: "dotted black", contain: "4 dark magenta bags." },
  { bagColor: "mirrored salmon", contain: "3 vibrant beige bags, 3 vibrant purple bags." },
  { bagColor: "dark green", contain: "4 dotted yellow bags, 1 faded green bag, 3 muted lavender bags." },
  { bagColor: "faded blue", contain: "4 clear turquoise bags, 1 posh indigo bag, 2 faded green bags." },
  { bagColor: "pale black", contain: "2 pale coral bags, 3 faded black bags, 3 mirrored teal bags, 4 muted chartreuse bags." },
  { bagColor: "plaid black", contain: "3 posh brown bags, 3 dark maroon bags, 1 mirrored black bag." },
  { bagColor: "dim olive", contain: "5 posh indigo bags." },
  { bagColor: "dark lavender", contain: "3 light gold bags, 5 dim purple bags." },
  { bagColor: "shiny turquoise", contain: "3 dim fuchsia bags, 4 faded silver bags, 4 dim salmon bags." },
  { bagColor: "light green", contain: "1 drab red bag." },
  { bagColor: "wavy plum", contain: "2 wavy gold bags, 5 bright tan bags." },
  { bagColor: "vibrant tan", contain: "3 drab gray bags." },
  { bagColor: "shiny orange", contain: "2 clear plum bags, 1 posh red bag." },
  { bagColor: "dull lime", contain: "3 pale silver bags." },
  { bagColor: "shiny cyan", contain: "3 shiny purple bags." },
  { bagColor: "posh brown", contain: "1 striped salmon bag, 2 dotted beige bags." },
  { bagColor: "mirrored blue", contain: "2 muted olive bags, 5 mirrored aqua bags." },
  { bagColor: "dark red", contain: "2 shiny purple bags, 4 dim salmon bags, 2 wavy salmon bags." },
  { bagColor: "wavy gray", contain: "4 striped fuchsia bags, 2 wavy salmon bags, 4 faded silver bags." },
  { bagColor: "clear gold", contain: "2 vibrant plum bags." },
  { bagColor: "dark silver", contain: "4 striped gold bags, 4 plaid teal bags, 1 pale yellow bag." },
  { bagColor: "dim cyan", contain: "4 mirrored blue bags, 1 vibrant red bag, 5 shiny indigo bags, 5 muted gray bags." },
  { bagColor: "bright chartreuse", contain: "4 light yellow bags, 3 faded lavender bags." },
  { bagColor: "dotted green", contain: "3 pale indigo bags, 3 drab gray bags, 2 dark white bags, 4 light yellow bags." },
  { bagColor: "vibrant bronze", contain: "5 light white bags, 1 dim lime bag, 5 dim brown bags, 5 plaid coral bags." },
  { bagColor: "muted purple", contain: "3 dark maroon bags." },
  { bagColor: "bright salmon", contain: "3 clear beige bags." },
  { bagColor: "mirrored lime", contain: "1 wavy coral bag, 1 mirrored gray bag." },
  { bagColor: "faded cyan", contain: "2 pale bronze bags, 3 vibrant plum bags." },
  { bagColor: "dull aqua", contain: "2 dark coral bags, 3 clear turquoise bags." },
  { bagColor: "posh aqua", contain: "1 pale teal bag, 2 dim coral bags." },
  { bagColor: "wavy aqua", contain: "2 posh indigo bags, 4 shiny cyan bags, 3 muted tan bags." },
  { bagColor: "dark magenta", contain: "1 pale red bag, 1 dull brown bag, 3 faded lavender bags." },
  { bagColor: "striped lavender", contain: "4 striped gold bags, 3 mirrored olive bags, 2 dim lime bags, 1 muted indigo bag." },
  { bagColor: "bright turquoise", contain: "no other bags." },
  { bagColor: "dim teal", contain: "5 dark white bags, 2 faded chartreuse bags, 1 striped beige bag, 4 muted gold bags." },
  { bagColor: "wavy yellow", contain: "4 pale fuchsia bags." },
  { bagColor: "muted black", contain: "1 striped salmon bag, 1 shiny gold bag, 3 plaid gray bags." },
  { bagColor: "dark beige", contain: "3 wavy gray bags, 5 dim red bags." },
  { bagColor: "mirrored tan", contain: "2 faded purple bags, 4 faded lime bags, 5 dull lavender bags, 4 dark plum bags." },
  { bagColor: "vibrant teal", contain: "1 dark teal bag, 4 dotted chartreuse bags." },
  { bagColor: "bright plum", contain: "1 vibrant silver bag." },
  { bagColor: "dotted purple", contain: "3 faded beige bags, 3 muted lavender bags." },
  { bagColor: "faded tomato", contain: "1 muted olive bag, 5 faded orange bags, 5 light yellow bags." },
  { bagColor: "light crimson", contain: "no other bags." },
  { bagColor: "drab fuchsia", contain: "2 vibrant silver bags, 1 dim fuchsia bag, 3 clear plum bags, 1 drab gold bag." },
  { bagColor: "muted blue", contain: "1 dotted silver bag, 5 dull beige bags, 3 posh silver bags." },
  { bagColor: "dark brown", contain: "1 clear red bag, 2 light yellow bags, 1 wavy gold bag, 2 plaid olive bags." },
  { bagColor: "dim gold", contain: "4 dotted purple bags, 3 plaid blue bags." },
  { bagColor: "dim crimson", contain: "5 muted magenta bags." },
  { bagColor: "shiny teal", contain: "1 dotted bronze bag, 4 vibrant teal bags, 4 pale blue bags." },
  { bagColor: "drab blue", contain: "3 dark salmon bags." },
  { bagColor: "bright olive", contain: "5 pale fuchsia bags." },
  { bagColor: "mirrored gold", contain: "2 posh brown bags, 2 bright purple bags, 5 shiny cyan bags." },
  { bagColor: "dim turquoise", contain: "4 pale cyan bags, 2 mirrored violet bags." },
  { bagColor: "clear silver", contain: "4 dark plum bags, 4 pale gray bags, 5 mirrored bronze bags." },
  { bagColor: "clear olive", contain: "4 muted green bags." },
  { bagColor: "drab lime", contain: "3 dotted aqua bags, 2 faded blue bags, 3 faded salmon bags, 3 dim yellow bags." },
  { bagColor: "dim fuchsia", contain: "no other bags." },
  { bagColor: "mirrored black", contain: "1 dark white bag." },
  { bagColor: "clear cyan", contain: "3 plaid chartreuse bags, 3 plaid teal bags, 5 dark gold bags, 5 dim lime bags." },
  { bagColor: "bright tomato", contain: "4 dark green bags." },
  { bagColor: "dim white", contain: "2 shiny yellow bags, 1 pale maroon bag." },
  { bagColor: "light turquoise", contain: "5 posh blue bags, 2 light fuchsia bags." },
  { bagColor: "shiny olive", contain: "5 vibrant white bags, 3 dark salmon bags, 5 dotted tan bags." },
  { bagColor: "striped maroon", contain: "1 mirrored olive bag." },
  { bagColor: "striped salmon", contain: "3 muted indigo bags, 5 wavy salmon bags, 4 shiny maroon bags, 4 dim fuchsia bags." },
  { bagColor: "striped orange", contain: "2 dotted purple bags, 4 shiny cyan bags, 1 drab gold bag, 4 dark beige bags." },
  { bagColor: "posh olive", contain: "3 faded tomato bags, 5 posh blue bags, 1 clear red bag." },
  { bagColor: "shiny plum", contain: "3 pale purple bags, 3 dim beige bags." },
  { bagColor: "dark olive", contain: "4 dull coral bags." },
  { bagColor: "dotted teal", contain: "5 plaid lavender bags, 4 clear bronze bags, 4 dim lime bags, 3 pale maroon bags." },
  { bagColor: "clear brown", contain: "2 wavy teal bags, 1 faded green bag, 5 light white bags." },
  { bagColor: "clear crimson", contain: "4 pale turquoise bags, 5 plaid green bags, 3 shiny aqua bags, 5 wavy turquoise bags." },
  { bagColor: "mirrored maroon", contain: "5 bright coral bags, 5 drab orange bags." },
  { bagColor: "wavy violet", contain: "4 mirrored tomato bags, 4 striped gold bags." },
  { bagColor: "plaid olive", contain: "3 dotted silver bags." },
  { bagColor: "light purple", contain: "2 dark red bags, 5 dull cyan bags, 4 plaid black bags." },
  { bagColor: "wavy orange", contain: "1 dim green bag, 4 dark coral bags." },
  { bagColor: "vibrant red", contain: "4 posh brown bags." },
  { bagColor: "wavy silver", contain: "5 faded orange bags, 2 wavy coral bags, 4 faded silver bags." },
  { bagColor: "dark tan", contain: "3 mirrored brown bags, 2 bright plum bags, 2 plaid silver bags." },
  { bagColor: "vibrant blue", contain: "1 wavy salmon bag, 5 pale green bags." },
  { bagColor: "shiny bronze", contain: "5 wavy white bags, 1 dim indigo bag, 5 muted crimson bags, 5 shiny lime bags." },
  { bagColor: "clear red", contain: "1 dotted aqua bag, 3 pale chartreuse bags, 2 muted teal bags, 5 posh brown bags." },
  { bagColor: "dotted silver", contain: "2 dark maroon bags, 3 dim brown bags." },
  { bagColor: "bright tan", contain: "1 posh black bag, 5 striped orange bags, 5 drab gold bags." },
  { bagColor: "drab red", contain: "5 posh gray bags." },
  { bagColor: "striped purple", contain: "1 striped silver bag, 1 pale blue bag, 4 mirrored black bags." },
  { bagColor: "striped bronze", contain: "2 striped gold bags, 5 light crimson bags, 5 faded tomato bags, 3 wavy indigo bags." },
  { bagColor: "pale red", contain: "2 mirrored olive bags, 5 faded orange bags, 4 faded chartreuse bags, 2 plaid chartreuse bags." },
  { bagColor: "dim plum", contain: "4 vibrant coral bags, 3 clear purple bags, 3 dull blue bags." },
  { bagColor: "muted yellow", contain: "2 clear red bags, 3 pale plum bags." },
  { bagColor: "posh salmon", contain: "3 pale tan bags, 3 wavy gold bags." },
  { bagColor: "mirrored bronze", contain: "4 faded bronze bags, 1 clear black bag, 5 dark white bags." },
  { bagColor: "muted cyan", contain: "2 dim plum bags." },
  { bagColor: "vibrant fuchsia", contain: "1 faded teal bag, 2 muted teal bags, 3 pale chartreuse bags, 3 bright teal bags." },
  { bagColor: "mirrored fuchsia", contain: "4 dull red bags, 1 light cyan bag, 3 wavy crimson bags, 3 wavy yellow bags." },
  { bagColor: "clear indigo", contain: "5 clear bronze bags, 4 dark coral bags, 4 drab chartreuse bags." },
  { bagColor: "pale bronze", contain: "2 faded salmon bags, 1 shiny black bag, 3 pale yellow bags, 3 dotted chartreuse bags." },
  { bagColor: "pale purple", contain: "4 mirrored black bags, 1 vibrant silver bag, 2 striped beige bags, 5 dotted chartreuse bags." },
  { bagColor: "muted gray", contain: "4 shiny purple bags, 4 light green bags, 1 pale fuchsia bag." },
  { bagColor: "clear blue", contain: "5 dotted olive bags, 4 light purple bags." },
  { bagColor: "posh cyan", contain: "5 muted tan bags, 1 dotted cyan bag, 4 wavy gold bags." },
  { bagColor: "bright purple", contain: "4 wavy salmon bags, 1 dark teal bag, 4 pale yellow bags." },
  { bagColor: "drab aqua", contain: "1 vibrant red bag." },
  { bagColor: "pale silver", contain: "4 light lavender bags, 2 mirrored bronze bags, 1 striped teal bag." },
  { bagColor: "dark blue", contain: "3 dull beige bags, 4 faded salmon bags, 1 dull black bag, 5 posh salmon bags." },
  { bagColor: "plaid tan", contain: "1 plaid lavender bag, 5 pale lavender bags, 4 light aqua bags." },
  { bagColor: "posh tan", contain: "3 dotted lime bags." },
  { bagColor: "drab maroon", contain: "5 mirrored chartreuse bags." },
  { bagColor: "dim magenta", contain: "1 pale fuchsia bag, 2 light fuchsia bags, 5 bright bronze bags, 1 faded gray bag." },
  { bagColor: "shiny purple", contain: "2 pale chartreuse bags." },
  { bagColor: "drab turquoise", contain: "4 light turquoise bags." },
  { bagColor: "light bronze", contain: "2 posh black bags, 3 dark yellow bags, 3 faded plum bags." },
  { bagColor: "plaid gold", contain: "4 dark teal bags, 4 shiny plum bags." },
  { bagColor: "dim maroon", contain: "2 clear plum bags, 3 striped aqua bags, 2 striped teal bags." },
  { bagColor: "drab coral", contain: "3 faded chartreuse bags, 2 drab plum bags, 3 faded red bags, 1 dark blue bag." },
  { bagColor: "faded gray", contain: "3 pale gray bags, 2 dull beige bags, 5 wavy indigo bags." },
  { bagColor: "dotted magenta", contain: "2 light salmon bags." },
  { bagColor: "light magenta", contain: "3 posh yellow bags, 3 dotted green bags, 1 drab violet bag." },
  { bagColor: "dotted cyan", contain: "2 faded plum bags." },
  { bagColor: "dim orange", contain: "5 light brown bags, 5 bright yellow bags." },
  { bagColor: "posh teal", contain: "1 faded beige bag, 5 mirrored gold bags, 5 bright teal bags." },
  { bagColor: "dim purple", contain: "2 light silver bags, 5 muted red bags, 1 mirrored gold bag, 2 posh orange bags." },
  { bagColor: "shiny tomato", contain: "3 striped coral bags, 3 dark plum bags, 5 plaid turquoise bags." },
  { bagColor: "vibrant olive", contain: "3 vibrant lime bags, 5 mirrored white bags, 1 pale bronze bag, 2 striped cyan bags." },
  { bagColor: "dull lavender", contain: "5 muted gold bags, 5 pale maroon bags." },
  { bagColor: "light black", contain: "1 dark plum bag, 1 shiny gold bag." },
  { bagColor: "bright magenta", contain: "3 striped turquoise bags, 3 dim gray bags." },
  { bagColor: "drab tomato", contain: "3 vibrant purple bags, 4 shiny purple bags, 2 light maroon bags." },
  { bagColor: "posh turquoise", contain: "2 bright aqua bags, 2 striped salmon bags, 5 muted green bags." },
  { bagColor: "dotted yellow", contain: "3 dark red bags, 3 wavy gold bags." },
  { bagColor: "plaid lavender", contain: "4 striped turquoise bags, 1 dotted olive bag, 1 clear green bag, 4 shiny beige bags." },
  { bagColor: "drab black", contain: "5 dotted magenta bags, 2 drab yellow bags, 2 striped turquoise bags, 1 dark bronze bag." },
  { bagColor: "clear beige", contain: "4 striped salmon bags." },
  { bagColor: "light lavender", contain: "1 wavy silver bag, 1 dark indigo bag." },
  { bagColor: "posh red", contain: "4 muted olive bags, 3 light tan bags, 4 clear gray bags, 2 dim lime bags." },
  { bagColor: "clear coral", contain: "3 light lime bags, 2 posh violet bags." },
  { bagColor: "plaid salmon", contain: "2 pale yellow bags, 5 dark plum bags." },
  { bagColor: "pale gold", contain: "2 striped teal bags, 3 faded crimson bags." },
  { bagColor: "wavy red", contain: "4 faded green bags, 5 dim coral bags, 4 wavy silver bags, 4 plaid brown bags." },
  { bagColor: "faded white", contain: "2 posh tomato bags, 1 posh green bag, 4 vibrant lavender bags." },
  { bagColor: "dull indigo", contain: "3 muted olive bags, 4 shiny purple bags, 3 drab chartreuse bags, 1 dotted orange bag." },
  { bagColor: "wavy green", contain: "3 pale indigo bags, 1 striped purple bag, 5 dotted coral bags, 1 shiny tan bag." },
  { bagColor: "shiny red", contain: "4 pale fuchsia bags, 2 posh salmon bags." },
  { bagColor: "vibrant cyan", contain: "1 faded salmon bag, 1 faded black bag, 4 striped coral bags." },
  { bagColor: "dark tomato", contain: "3 clear maroon bags, 4 plaid maroon bags, 5 dotted aqua bags." },
  { bagColor: "vibrant gold", contain: "1 shiny fuchsia bag." },
  { bagColor: "dark black", contain: "2 wavy lime bags, 1 pale cyan bag, 4 posh brown bags." },
  { bagColor: "posh fuchsia", contain: "4 pale purple bags, 2 dull lavender bags." },
  { bagColor: "light silver", contain: "2 vibrant plum bags, 2 pale magenta bags, 4 pale chartreuse bags, 3 plaid chartreuse bags." },
  { bagColor: "dark yellow", contain: "1 dotted crimson bag, 3 faded orange bags, 5 posh teal bags, 1 clear plum bag." },
  { bagColor: "mirrored turquoise", contain: "2 muted teal bags." },
  { bagColor: "drab purple", contain: "5 dotted plum bags, 1 plaid plum bag." },
  { bagColor: "dotted tan", contain: "1 pale plum bag, 1 dotted aqua bag." },
  { bagColor: "drab bronze", contain: "4 vibrant red bags, 4 light blue bags." },
  { bagColor: "mirrored cyan", contain: "1 dark white bag, 4 dark lime bags, 5 vibrant silver bags." },
  { bagColor: "shiny aqua", contain: "5 wavy plum bags, 4 drab maroon bags, 2 drab chartreuse bags." },
  { bagColor: "striped aqua", contain: "1 plaid blue bag, 1 dark plum bag, 4 faded lavender bags." },
  { bagColor: "dotted plum", contain: "5 mirrored green bags, 1 dark plum bag, 4 dark maroon bags." },
  { bagColor: "faded gold", contain: "4 pale yellow bags." },
  { bagColor: "vibrant beige", contain: "2 light lavender bags, 3 faded indigo bags." },
  { bagColor: "light brown", contain: "3 drab brown bags, 4 dark violet bags, 3 faded indigo bags." }
]
let result = document.querySelector(".result")

// Set bagrules, so not passed to recursive function
let bagrules = puzzle_bagrules

const getTotalBagCount = (selectedBagColor) => {
  let foundBag = bagrules.find( x => x.bagColor === selectedBagColor )
  let bagTokens = foundBag.contain.split(" ")
  let totalBagCount = 0
  let index = 0
  while (index < bagTokens.length) {
    let bagCount = parseInt(bagTokens[index])
    if (bagCount) {
      // Assume next 2 tokens is Bag Color
      let bagColor = bagTokens[index+1] + " " + bagTokens[index+2]
      totalBagCount += bagCount + bagCount*(getTotalBagCount(bagColor))
      index += 2
    }
    index++
  }
  return totalBagCount
}

result.innerHTML = "2020 Question 7A - Total Bag Count for Shiny Gold Bag = " + getTotalBagCount("shiny gold")